### PR TITLE
feat: add component catalog for components/ui/*

### LINKED ISSUE #323: Add a component catalog (Storybook or Ladle) for components/ui/*
## Problem

Follow-up to #322. The first phase of formalizing the design system (docs/design-system.md, primitive consolidation, accessibility pass, contribution guideline) intentionally deferred the component catalog piece to keep that PR scoped and reviewable.

## Proposal

Add a browsable, testable catalog for the shared primitives in `frontend/src/app/components/ui/*` (button, input, dropdown-menu, toggle-switch, search-bar, pill-button, tab-pill-button, cite-button, liquid-dropdown, liquid-surface, plus whatever #322 adds).

Pick between Storybook and a lighter alternative (e.g. Ladle) based on actual setup/maintenance cost for this repo — Storybook is the industry default but has real ongoing overhead for a small OSS frontend; Ladle is a lighter Storybook-compatible alternative worth evaluating first.

Scope to `components/ui/*` only, same as #322 — don't try to catalog all 144 components in `frontend/src/app/components/` up front.

## Acceptance criteria

- [ ] Catalog tool chosen and documented (why, in the PR description)
- [ ] Stories/examples for each primitive in `components/ui/*`
- [ ] Catalog builds/runs cleanly (smoke-tested in CI or locally)
- [ ] Linked from `docs/design-system.md` (added in #322)

## Depends on

#322 (docs/design-system.md should exist first so this can link to it)

### LINKED ISSUE #408: fix: package-lock.json out of sync with package.json — npm ci fails in CI (PR #407)
## Summary

On PR #407 (`feat/323-component-catalog`, head `6869402`), CI's `npm ci` step fails deterministically in both the `Frontend build and tests` and `playwright` jobs, with:

```
npm error code EUSAGE
npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm error
npm error Missing: @swc/helpers@0.5.23 from lock file
npm error Missing: esbuild@0.28.2 from lock file
npm error Missing: @esbuild/aix-ppc64@0.28.2 from lock file
... (all esbuild platform binaries for 0.28.2)
```

This means CI cannot even install frontend dependencies on this branch — `test:coverage`, `lint`, `build`, and the new `catalog:build` gate are all **skipped as a consequence** (see job step list: only `npm ci` runs and fails; everything after is marked `skipped`).

## Root cause

The lockfile changes adding `@ladle/react` (and its transitive deps) are internally inconsistent — `package-lock.json` is missing lockfile entries (`@swc/helpers@0.5.23`, `esbuild@0.28.2` + all platform binaries) that the committed `package.json`'s dependency tree requires. Confirmed:

- These packages/versions do not exist anywhere in `origin/main`'s lockfile — this is 100% new content introduced by this PR's `@ladle/react` addition, not a pre-existing issue.
- Locally, `npm ci` on this branch succeeds under npm 11.16.0 / Node 24.18.0, but CI (which pins `node-version: 22`, so an older bundled npm) fails with the "out of sync" error. This points to the lockfile having been generated/committed with a newer npm than CI uses, producing a lockfile shape that an older `npm ci` rejects as inconsistent.

## Evidence

- CI run (Frontend build and tests): https://github.com/open-legal-products/mike/actions/runs/33424474173/job/99594582005
- CI run (playwright): https://github.com/open-legal-products/mike/actions/runs/33424474128/job/99594581976
- Both fail at the `npm ci` step specifically, ~19s in, before any test/build step runs.

## Suggested fix

Regenerate `frontend/package-lock.json` using an npm version that matches (or is older than / compatible with) what CI's `actions/setup-node@v4` with `node-version: 22` provisions, then re-commit. Verify with a clean `npm ci` (not `npm install`) under that same npm version before pushing — `npm install` can silently "repair" an inconsistent lockfile in a way `npm ci` will not accept, which is how this got past local testing.

## Context

Filed during PR review of #407 (component catalog / Ladle setup, closes #323). Everything else in that PR — the Ladle setup itself, the Tailwind dot-directory handling, story coverage, docs — checked out; this lockfile issue is the sole blocker.

### PR DESCRIPTION
**Pull request by bmersereau**
## Summary

Adds a browsable component catalog for the primitives in
`frontend/src/app/components/ui/`, using **Ladle**. 48 stories cover all 17
primitives currently in that directory. The catalog is linked from
`docs/design-system.md` and smoke-built in CI.

Closes #323
Closes #408

## Why Ladle and not Storybook

The issue asked for the choice to be made on actual setup and maintenance cost
for this repo, not on which tool is more popular. Four things decided it:

1. **Nothing in `components/ui/` imports from `next/*`.** I grepped both
   `components/ui/` and `shared/ui/` and there are zero Next.js imports — the
   primitives are plain React plus `lucide-react`, `clsx` and `tailwind-merge`.
   That removes the single biggest reason to reach for Storybook here, since
   `@storybook/nextjs` exists mainly to shim `next/image`, `next/font` and the
   router. We would be paying for a compatibility layer with nothing to
   compatibility-layer.
2. **One devDependency instead of a package set.** Ladle is a single
   `@ladle/react` entry. A Storybook install for this stack is the `storybook`
   core plus a framework package plus the addons you actually want, each on its
   own release cadence, plus periodic `storybook upgrade` migrations. For a
   small OSS frontend that is recurring maintenance nobody is assigned to.
3. **The repo already runs Vite.** Vitest and `@vitejs/plugin-react` are
   installed, so Ladle reuses the transform pipeline and `@/` alias resolution
   the tests already use. One build system, one mental model.
4. **The exit is cheap.** Stories are CSF-compatible — `export default { title }`
   plus named exports — so if the project outgrows Ladle the stories port to
   Storybook without a rewrite. Choosing the light tool first is reversible;
   choosing the heavy one is not.

Trade-off accepted: Ladle has a smaller addon ecosystem and no Chromatic-style
visual-regression story. Neither is in scope for #323, and #322 established the
design system as documentation-first.

## What changed

- `frontend/.ladle/config.mjs` — story glob scoped to
  `src/app/components/ui/*.stories.tsx`, per the issue's "don't catalog all 144
  components" constraint. a11y addon on, rtl and msw off.
- `frontend/.ladle/components.tsx` — global Provider. Mike's dark mode is
  class-based (`@custom-variant dark (&:is(.dark *))`), so the Provider drives
  the same `.dark` class on the document root that Settings > Appearance sets.
  Without this the theme toggle would flip Ladle's own chrome and leave every
  app token on its light value.
- `frontend/.ladle/ladle.css` — imports the app's real `globals.css` so the
  catalog renders on the actual tokens and materials rather than a copy, and
  supplies the two font variables that `next/font` normally injects on `<body>`.
- 17 `*.stories.tsx` files colocated with their primitives, matching the
  existing `*.test.tsx` convention.
- `docs/design-system.md` — new "Component catalog" section; removed the
  "tracked in issue #323, not set up yet" line.
- `.github/workflows/ci.yml` — `npm run catalog:build --if-present` after the
  frontend build.
- `frontend/package.json` — `@ladle/react` devDependency plus `catalog` and
  `catalog:build` scripts.

## Coverage

All 17 primitives in `components/ui/`: `button`, `check-square`, `cite-button`,
`dropdown-menu`, `empty-state`, `form-field`, `glass-card`,
`glass-icon-button`, `input`, `liquid-dropdown`, `liquid-surface`,
`option-pill`, `pill-button`, `popover`, `search-bar`, `tab-pill-button`,
`toggle-switch`.

The issue listed the primitives as of filing; the directory has grown since, so
I enumerated it rather than working from that list. `liquid-surface.ts` is
class-name constants rather than a component, but it gets stories anyway — the
elevation ladder is the part of the design system hardest to hold in your head
from prose, and swatches of each material and interactive state are the clearest
way to show it.

Stories lean on documenting the sharp edges the design system already calls
out: `Button` has no `type` default so it submits inside a `<form>`;
`CiteButton` only sets `aria-label` when its text is hidden (WCAG 2.5.3);
`CheckSquare` is decorative and the row owns the ARIA state.

## One non-obvious thing worth flagging in review

Tailwind v4's automatic source detection **skips dot-directories**, so nothing
in `frontend/.ladle/` is scanned for class names, and an `@source` override
does not lift that exclusion. I found this by probing with a class used nowhere
else and confirming it was absent from the built CSS.

The first version of the Provider happened to work only because every utility
it used also appears somewhere in `src/`. That is a trap: the next person to
add a novel Tailwind class to the Provider would get silently unstyled output.
Catalog chrome is therefore styled with plain CSS in `.ladle/ladle.css`, and
both that file and `docs/design-system.md` say why. Story files live under
`src/` and are scanned normally, so Tailwind works as expected in a
`*.stories.tsx`.

## Testing performed

Config/tooling change, so the regression check is a build gate rather than
component unit tests — the primitives already have their own `*.test.tsx`
suites.

- `npm run catalog:build --prefix frontend` — passes, 48 stories across 17
  primitives in `meta.json`.
- Verified the built CSS actually resolves the design system rather than just
  compiling: `liquid-glass-flat`, `liquid-glass-modal-row-selected`,
  `theme-dropdown-item`, and both the light (`#f9fafb`) and dark (`#0b0f14`)
  `--app-background` values are present.
- Ran the built catalog and loaded it in a browser: stories render, dark mode
  toggles the real dark tokens, the Radix dropdown opens and portals onto the
  float glass surface, no console errors.
- `npm run build --prefix frontend` — passes. Confirmed stories are inside the
  TS program by injecting a deliberate bad prop (`tone="not-a-real-tone"`) and
  checking `tsc` caught it, then reverting; this is what backs the claim that
  CI catches story/prop drift.
- `npm run lint --prefix frontend` with the ESLint cache cleared — 0 errors, 34
  warnings, which is exactly the pre-existing baseline. My first pass added 17
  `no-anonymous-default-export` warnings, so the default exports are now named
  consts.
- `npm run test:coverage --prefix frontend` — 637 passed, 4 failed, all 4 in
  `src/app/lib/mikeApi.test.ts` (`blob.text is not a function`).

  **Those 4 failures are pre-existing and not caused by this PR.** I verified
  rather than assumed: they reproduce identically after checking out
  `origin/main`'s `package.json` and `package-lock.json` and reinstalling, with
  none of this branch's dependencies present. A lockfile diff also shows zero
  version changes to any pre-existing package — the 166 lockfile additions are
  new Ladle dependencies and the 27 removals are all deduped nested esbuild
  platform binaries. The failures are a local Node 24 vs CI Node 22 jsdom/Blob
  difference; CI on `main` at `6c77dda` is green, so per the repo's guidance on
  toolchain mismatches I have not filed an issue for them.

## Lockfile fix for #408

CI's `npm ci` was failing in both the frontend and playwright jobs with
`Missing: @swc/helpers@0.5.23` and `Missing: esbuild@0.28.2` (plus platform
binaries). Root cause: the lockfile above was generated locally with npm
11.16.0 (Node 24), and that npm silently accepted a shape that CI's npm
10.9.8 (bundled with the pinned Node 22) rejects as out of sync with
`package.json`.

Fixed by installing an actual Node 22 (v22.23.2 / npm 10.9.8, matching what
CI's `actions/setup-node@v4` with `node-version: 22` provisions) and running
`npm install` against the existing lockfile in place, rather than deleting
and regenerating it from scratch — a full wipe re-resolves every
caret-ranged dependency to today's registry latest and would have dragged in
hundreds of unrelated version bumps. The in-place repair only touches what
was actually inconsistent:

- 167 additions, all `@ladle/react` transitive deps (including
  `@vitejs/plugin-react-swc`'s nested `@swc/helpers@0.5.23`, one of the two
  packages CI's error named).
- 0 removals.
- 27 version changes, all of them the `esbuild` instance nested under
  `vitest` moving from `0.28.1` to `0.28.2` — the second package CI's error
  named, and the version the rest of the tree already needed.

Verified: `npm ci` (fresh `node_modules` wipe) exits 0 with no
missing/invalid/extraneous warnings, `npm run catalog:build` still produces
48 stories, `npx vitest run` / `npm run test:coverage` pass all 641 tests
(also confirming the 4 `mikeApi.test.ts` failures noted above are Node
24-only — they pass under Node 22), `npx tsc --noEmit` is clean, `npm run
lint` is unchanged at 0 errors / 34 warnings, and `npm run build` (`next
build`) succeeds. All run under the same Node 22 toolchain CI uses.

### CODE REVIEW

**Comment by revoirsoftware** [comment]
## PR Review: feat: add component catalog for components/ui/*

### Summary
Adds a Ladle-based component catalog for the 17 primitives in `frontend/src/app/components/ui/` (48 stories total), a CI smoke-build gate, and a new "Component catalog" section in `docs/design-system.md`. The tooling choice (Ladle over Storybook) is well-argued and independently checks out: zero `next/*` imports in the target directory, reuse of the existing Vite/Vitest pipeline, CSF-compatible stories. Closes #323. One real blocker found: the committed lockfile is not `npm ci`-consistent, which fails CI's dependency install step entirely.

### Risk Assessment
- **Risk Level**: Medium (dev-tooling only, zero production code touched — but CI is currently broken on this branch)
- **Blast Radius**: Contained to `frontend/.ladle/`, `*.stories.tsx` files, `docs/`, and CI config. No production runtime path changes. The lockfile issue blocks CI for this branch only, not `main`.
- **Rollback Plan**: Trivial — revert the 4 commits, no migrations, no runtime surface touched.

### Verified Independently (not taken on faith)

**1. Tailwind v4 dot-directory claim — confirmed real.**
`frontend/.ladle/ladle.css` and `.ladle/components.tsx` use plain CSS / CSS custom properties (`var(--app-background)`, `var(--color-gray-700)`, `var(--font-sans)`) with no Tailwind utility classes or `@apply`. I reproduced the underlying claim by injecting an unused arbitrary-value Tailwind class (`tracking-[0.019em]`) into `.ladle/components.tsx` (the dot-directory file) and rebuilding: the class produced **zero** CSS output. Reverted cleanly afterward (`git diff` empty). This confirms Tailwind v4 really does skip dot-directories even with the file living one level under a scanned root, and that the PR's fix (plain CSS for catalog chrome) is the correct one, not a misdiagnosis.

Also confirmed the specific design-token claims in the PR body against the actual built CSS (`ladle build` output):
- `--app-background:#f9fafb;` (light) and `--app-background:#0b0f14;` (dark) both present, each exactly once.
- `liquid-glass-flat`, `liquid-glass-modal-row-selected`, `theme-dropdown-item` all present.
These come from `globals.css`'s real `:root`/`.dark` custom properties (imported via `@import "../src/app/globals.css"` in `ladle.css`), so they're immune to the dot-directory exclusion regardless — they're plain CSS custom properties, not Tailwind-generated utilities.

**2. Pre-existing `mikeApi.test.ts` failure claim — confirmed pre-existing, not caused by this PR.**
Ran `npx vitest run src/app/lib/mikeApi.test.ts` on the PR branch: **4 failed / 174 passed**, all `TypeError: blob.text is not a function`, matching the PR's description exactly. Cross-referenced against PR #406 (open, not yet merged), which fixes this exact issue (#361) at the Vitest-setup level by restoring the native `node:buffer` Blob after jsdom overrides `globalThis.Blob`. A prior review of #406 in this session independently reproduced the same 4 failures on `origin/main` by reverting `vitest.setup.ts`, confirming the mechanism. Since #406 is not yet merged, these 4 failures being present on #407 (which predates #406) is expected and not a new blocker — **no duplicate issue filed**. Once #406 merges, this branch will need a rebase to pick up the fix, not a code change of its own.

**3. Lockfile diff claim ("166 additions are Ladle's own deps, 27 removals are deduped esbuild binaries, zero pre-existing version changes") — confirmed precisely.**
Diffed `packages` entries between `origin/main` and PR head's `package-lock.json` programmatically: **166 added packages, 27 removed packages, 0 version changes to any pre-existing package**. The 27 removals are exactly the nested `node_modules/vitest/node_modules/@esbuild/*` platform binaries (deduped to top-level once Ladle's own esbuild dependency forces hoisting). The added packages are Ladle/MDX/inquirer/swc-core/msw-interceptor deps — all attributable to `@ladle/react`.

**4. Catalog build + story count — ran it myself, did not trust the PR's number.**
`npm run catalog:build` in the PR's own worktree (already had deps installed) succeeds. Parsed the emitted `build/meta.json`: **48 stories across exactly 17 distinct `filePath` values**. Cross-checked those 17 story files 1:1 against the actual non-story, non-test contents of `frontend/src/app/components/ui/` — exact match, confirming the "enumerated the directory rather than trusting the issue" claim in the PR body.

Also confirmed `npm run lint --prefix frontend` produces exactly 0 errors / 34 warnings, all in pre-existing files unrelated to this PR (`MfaLoginGate.tsx`, `DocxView.tsx`, `TRChatPanel.tsx`, `TRSidePanel.tsx`, `TabularCell.tsx`) — matching the claimed "exactly the pre-existing baseline."

### Review by Category

#### Correctness
- [severity:praise] The Tailwind dot-directory trap is a genuinely non-obvious Tailwind v4 behavior, correctly diagnosed, correctly fixed (plain CSS for catalog chrome, not a workaround like forcing an `@source` override that the PR body notes doesn't even work), and documented in three places (PR body, `ladle.css` comment, `docs/design-system.md`) so the next contributor doesn't rediscover it the hard way.
- [severity:blocker] **`frontend/package-lock.json` is not `npm ci`-consistent with `frontend/package.json`.** CI's `npm ci` step fails in both the `Frontend build and tests` and `playwright` jobs with `npm error code EUSAGE ... Missing: @swc/helpers@0.5.23 from lock file`, `Missing: esbuild@0.28.2 from lock file` (plus all its platform binaries). This is new content introduced by this PR — neither package/version appears anywhere in `origin/main`'s lockfile. Every step after `npm ci` (test:coverage, lint, build, and the new `catalog:build` gate this PR adds) is skipped as a direct consequence. Locally, `npm ci` succeeds under npm 11.16.0/Node 24.18.0, but CI pins `node-version: 22` (an older bundled npm), which rejects the lockfile as out of sync — consistent with the lockfile having been generated/committed with a newer npm than CI provisions. `npm install` (which the author used for local testing per the PR's testing section) can silently repair this kind of inconsistency in a way `npm ci` will not accept, which is how it passed local checks but not CI. Filed as https://github.com/open-legal-products/mike/issues/408. **Must fix before merge** — regenerate the lockfile with a Node-22-compatible npm and verify with `npm ci` (not `npm install`) before pushing.

#### Security
- N/A — dev-tooling and documentation only, no production runtime path touched. No secrets, no user input handling, no XSS-relevant patterns (`grep` for `dangerouslySetInnerHTML`/`eval` in all new files: clean).

#### Performance
- N/A. Catalog build output (~1.67 MiB, mostly Ladle's own `axe-core` and `react-inspector` bundles) is dev-tooling-only and does not ship in the production Next.js bundle.

#### Test Coverage
- No new unit tests, correctly — this is a tooling/config change with a build-gate as the regression check (stories are type-checked by `next build` via the shared `tsconfig.json` `**/*.tsx` include, and bundled by `ladle build`), which is the appropriate level of rigor for this kind of change. Verified `tsconfig.json` has no exclude carving out `.ladle/` or `*.stories.tsx`, and `next.config.*` has no `typescript.ignoreBuildErrors` escape hatch that would make the "CI catches story/prop drift" claim false.
- CI state at review time (point-in-time snapshot, not blocking the verdict by itself, but shaping it per the failure classification above): `Frontend build and tests` FAIL, `playwright` FAIL (both at `npm ci`, root-caused above), `Backend build and tests`/`CodeQL`/`Eval harness`/`Supabase stack integration tests`/`Fresh install vs upgraded deployment`/`gitleaks`/`license-cla` all PASS.

#### Code Quality
- [severity:praise] Stories double as living documentation of the design system's sharp edges (`Button`'s missing `type` default, `CiteButton`'s conditional `aria-label`, `CheckSquare`'s decorative-by-default ARIA delegation) rather than being trivial prop-permutation dumps. `check-square.stories.tsx`'s `InAPickerRow` story implements a fully correct roving `role="checkbox"`/`aria-checked`/keyboard (`Space`/`Enter`) pattern, not just a static render.
- [severity:nit] `liquid-surface.stories.tsx` renders `MATERIALS`/`PANELS`/`STATES` as `[label, className][]` tuples mapped with template-literal class interpolation — fine for a one-off catalog file, not worth abstracting further.

#### Documentation
- `docs/design-system.md` update is accurate to the actual behavior (verified the two "worth knowing" callouts against the real `ladle.css` and the dot-directory finding above) and removes the stale "tracked in issue #323, not set up yet" line.

#### Issue Lifecycle
- PR body contains `Closes #323` — correct closing keyword, will auto-close on merge.

#### Branch Hygiene
- 4 commits, all conventional (`feat:`/`fix:`/`docs:`), no merge commits, branch fresh off `origin/main` (merge-base == tip, verified). No AI/Claude attribution in any commit message (checked explicitly per repo policy).

### Test Coverage Assessment
- Lines added: ~3,850 (dominated by `package-lock.json` at +2,754; actual authored code is ~1,100 lines across 17 story files + 3 Ladle config files + docs)
- Test lines added: 0 (by design — see Test Coverage category above)
- Coverage delta: N/A (tooling change)
- Missing test cases: none expected for this kind of change

### Questions
1. Was the lockfile generated locally with a newer npm than CI's `node-version: 22` provisions? (Answered from evidence above: yes, very likely — local `npm ci` succeeds under npm 11.16.0/Node 24.18.0 while CI's npm rejects the same lockfile as out of sync, and the missing entries are 100% new content from this PR.)
2. Does #406 need to merge before #407, or can they merge independently? (Answered: independent — #407's 4 pre-existing `mikeApi.test.ts` failures are unrelated to Ladle and already tracked/fixed by the open #406; #407 just needs a rebase after #406 lands, not a code change of its own.)

### Suggestions (Non-Blocking)
- None beyond the nit above.

### Verdict
- [x] **Request changes** - Blocking issue (lockfile/`npm ci` failure, https://github.com/open-legal-products/mike/issues/408) must be addressed. Everything else — the Ladle setup, the Tailwind dot-directory fix, story coverage and quality, docs — is solid and independently verified.

### What I Verified
- [x] Read the full diff (`git diff origin/main..pr-407-head`, all 24 changed files)
- [x] Ran tests/build locally: `npm run catalog:build` (48 stories/17 files confirmed via `meta.json`), `npm run lint` (0 errors/34 warnings, all pre-existing), `npx vitest run src/app/lib/mikeApi.test.ts` (4 pre-existing failures reproduced), mutation-tested the Tailwind dot-directory claim by injecting and rebuilding, `npm ci` (reproduced success locally but confirmed CI's failure via actual CI logs — see blocker)
- [x] Checked related code not in diff (`globals.css` token definitions, `tsconfig.json` include globs, `next.config.*` for typecheck bypass, `origin/main`'s lockfile for pre-existing package presence)
- [x] Reviewed linked issue #323 and cross-referenced open PR #406 for the pre-existing test failure

**Comment by revoirsoftware** [comment]
## PR Re-Review (Round 2): feat: add component catalog for components/ui/*

### Summary
This is a re-review focused entirely on the fix for issue #408 (`npm ci` lockfile inconsistency), landed as commit `8b39f25`. Everything from round 1 (Tailwind v4 dot-directory trap, 17-primitive/48-story scope, docs linking) was confirmed unchanged by this commit and is not re-litigated here. **The #408 fix is verified genuinely correct and complete** — recomputed independently, not taken on trust.

### What I verified

**1. Lockfile diff, recomputed independently (not trusting the PR body's numbers)**

Wrote a small script to parse the `packages` object of `frontend/package-lock.json` on both `origin/main` and `HEAD` and diff at the package level (not raw line diff, which is misleading for JSON):

```
packages added:   167
packages removed: 0
version changed:  27  (all node_modules/vitest/node_modules/@esbuild/* and the top-level
                        esbuild instance nested under vitest, 0.28.1 -> 0.28.2)
```

This matches the PR body's claim exactly. I also cross-checked that `frontend/package.json` only adds one new devDependency (`@ladle/react@^5.1.1`) plus two scripts — nothing else. For the 167 additions, I flagged everything my regex didn't immediately recognize as Ladle-related (93 packages — `koa`, `msw`, `graphql`, `chokidar`, `boxen`, `history`, `prism-react-renderer`, `react-hotkeys-hook`, `open`, `query-string`, etc.) and confirmed with `npm ls <pkg> --all` against the freshly-installed tree that every one of them resolves as a transitive dependency of `@ladle/react@5.1.1` and nothing else. So: the 167 additions are genuinely 100% Ladle's dependency tree, not scope creep.

One nuance worth recording: there are also 27 entries (Rollup platform-optional packages, e.g. `@rollup/rollup-android-arm-eabi`) that changed a metadata field (a dropped `"peer": true` flag) at the *same* version between `main` and `HEAD`. I verified these are byte-identical between the pre-fix commit (`6869402`) and the fix commit (`8b39f25`) — i.e., they were introduced by round 1's original lockfile generation, not by the #408 fix. Not a new finding, just noting it so the "167/0/27" figures aren't misread as the complete diff.

**2. `npm ci` reproduction, isolated worktree, CI's exact toolchain**

Used Homebrew's `node@22` (22.23.2 / npm 10.9.8 — the same versions `actions/setup-node@v4` with `node-version: 22` provisions, and what the author claims to have tested with) in a scratch worktree at `8b39f25`:

```
$ rm -rf node_modules && npm ci
...
added 1413 packages, and audited 1414 packages in 12s
```

Grepped the full output for `missing|invalid|extraneous` (the exact failure mode #408 tracked) — zero matches, exit code 0. This is the specific thing that was broken before and is now fixed. (There are unrelated `ERESOLVE` peer-dependency *warnings* for `react-inspector` wanting React ^16-18 against the project's React 19 — pre-existing category of noise from adding Ladle at all, not a lockfile-consistency problem, doesn't affect `npm ci` exit status.)

**3. Full verification chain, same Node 22 toolchain, foreground, all before posting this review**

| Command | Result |
|---|---|
| `npm run catalog:build` | Passes. `build/meta.json` → `stories` object has exactly 48 keys, matching round 1. |
| `npx vitest run` | 98 files / **641 passed**, 0 failed — including the 4 `mikeApi.test.ts` cases that fail under Node 24. Confirms the author's claim that those are Node 24-only jsdom/Blob issues and don't reproduce under CI's pinned Node 22. |
| `npx tsc --noEmit` | Clean, 0 errors. |
| `npm run lint` | 0 errors, 34 warnings — matches the stated pre-existing baseline exactly. |
| `npm run build` | Succeeds, all 41 routes generated. |

**4. Round-1 content untouched**

`git diff 6869402..8b39f25 --name-only` (the commit immediately before the fix vs. the fix itself) shows exactly one file: `frontend/package-lock.json`. Nothing else in the diff moved.

**5. Branch/CI state**

- `origin/main`..`fork/feat/323-component-catalog` merge-base check: fresh, not stale.
- 5 commits, matches PR description, no stray commits.
- PR #406 (separate Node-24 `mikeApi.test.ts` fix, #361) is still **OPEN**, not merged — so this branch is not stale relative to it. As predicted, my local run under Node 22 shows all 4 of those tests passing anyway (Node 22 doesn't hit the bug), consistent with the theory that #406 fixes a Node-24-only issue.
- `gh pr checks 407` at review time: all 10 checks green, including `Frontend build and tests` and `playwright` (the two that were red before the fix) — both went green partway through my local verification. Recorded as a point-in-time snapshot, not something I waited on; my local reproduction above is the actual evidence for the verdict.

### Verdict
- [x] **Approve** - Ship it

Issue #408 is genuinely fixed, not just closed by convention. No new blockers or majors found in this round.

### Questions
None.

### What I Verified
- [x] Read the full diff of the fix commit (`8b39f25`) and independently recomputed the lockfile's package-level diff
- [x] Ran `npm ci` from a clean `node_modules` in an isolated worktree, on CI's exact Node/npm versions
- [x] Ran the full verification chain locally (catalog:build, vitest, tsc, lint, build) — all foreground, all before this comment was posted
- [x] Confirmed round 1's reviewed content is untouched by this round's commit
- [x] Checked PR #406's state and branch freshness
- [x] Checked `gh pr checks` as a point-in-time snapshot (did not wait on it)

**Comment by willchen96** [comment]
## Follow-up changes

This branch has been rebased onto the current `main` and expanded to include the review follow-ups:

- Moved web and cross-target stories into dedicated `stories/` directories under `components/ui` and `shared/ui`.
- Added both primitive collections to Ladle, with 69 stories now included in the production catalog build.
- Removed the unused generic `Button` component and its dependency on `class-variance-authority`.
- Removed the thin `GlassCard`, `GlassIconButton`, and `PillButton` web adapters. Web consumers now use their canonical `shared/ui` implementations directly.
- Consolidated the duplicated web and Word add-in `TabPillButton` and `ToggleSwitch` implementations into shared primitives, then updated all consumers in both targets.
- Replaced `PillButton asChild` usage with the server-safe `pillButtonUIClassName` helper on semantic links.
- Added a story for the current Markdown editor and updated stories for current component APIs, responsive widths, accessible names, loading states, and switch contrast.
- Updated the design-system documentation and made `npm run catalog:build` a required CI step.

### Verification

- Frontend tests: 181 files and 1,233 tests passed.
- Focused shared UI/editor tests: 36 passed.
- Frontend TypeScript, lint (0 errors), and production build passed.
- Ladle production build passed with all 69 stories.
- Word add-in typecheck and production build passed.
- `git diff --check` passed.

One non-blocking upstream warning remains: Ladle 5.1.1 depends on `react-inspector@6.0.2`, whose peer metadata does not yet list React 19. Installation and the catalog build both complete successfully.

**Review by willchen96 — APPROVED** [review]

**Comment by willchen96** [comment]
Thanks @bmersereau !
